# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "CentOS71"

  config.vm.define "web01" do |atomic|
    atomic.vm.hostname = "web01.example.com"
    config.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "web02" do |atomic|
    atomic.vm.hostname = "web02.example.com"
    config.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.define "ap01" do |atomic|
    atomic.vm.hostname = "ap01.example.com"
    config.vm.network "private_network", ip: "192.168.33.13"
  end

  config.vm.define "db01" do |atomic|
    atomic.vm.hostname = "db01.example.com"
    config.vm.network "private_network", ip: "192.168.33.14"
  end

end
